// =====================================================================================
// Name: Luc de Marillac St Julien
// Student Number: ST10382638
// Group: 1
//
// References:
//   1) Project outline/instructions: https://chatgpt.com/c/68f2c6ad-b79c-832c-97a1-59b6f53334a9
//   2) C# Reference & Tutorials:   https://www.w3schools.com/cs/index.php
// =====================================================================================

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ST10382638_PROG_POE.Models
{
    /// <summary>
    /// Represents a lecturer's claim for payment. 
    /// Contains details such as hours worked, rate, calculated amount,
    /// notes, status, submission timestamp, and references to related lecturer
    /// profile and supporting documentation.
    /// </summary>
    public class Claim
    {
        /// <summary>
        /// Primary key (identity column) for the claim.
        /// Auto-generated by the database on insert.
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ClaimId { get; set; }

        /// <summary>
        /// Foreign key linking the claim to a <see cref="LecturerProfile"/>.
        /// Required for establishing ownership of the claim.
        /// </summary>
        [Required]
        public int LecturerProfileId { get; set; }

        /// <summary>
        /// Number of hours worked being claimed. 
        /// Validated in controllers for bounds (e.g., 0.25–10).
        /// </summary>
        [Required]
        [Range(0.25, 10.0, ErrorMessage = "Hours must be between 0.25 and 10.0.")]
        public double HoursWorked { get; set; }

        /// <summary>
        /// Hourly rate applicable at the time the claim was submitted.
        /// Captured at submission to avoid changes if rates are updated later.
        /// </summary>
        [Required]
        public double RateAtSubmission { get; set; }

        /// <summary>
        /// Total amount for the claim, computed as HoursWorked × RateAtSubmission.
        /// This is calculated server-side for integrity and consistency.
        /// </summary>
        [Required]
        public double CalculatedAmount { get; set; }

        /// <summary>
        /// Optional notes from the lecturer when submitting the claim.
        /// Can be used for additional context (e.g., task description).
        /// </summary>
        [MaxLength(200)]
        public string? Notes { get; set; }

        /// <summary>
        /// Current status of the claim in the workflow.
        /// Typical values: "Pending", "Verified", "Approved", "Rejected".
        /// </summary>
        public string Status { get; set; }

        /// <summary>
        /// Date and time when the claim was submitted.
        /// Stored in UTC+2 (South Africa local time).
        /// </summary>
        public DateTime SubmittedOn { get; set; }

        /// <summary>
        /// Navigation property to the owning lecturer profile.
        /// Enables EF Core relationship and object graph traversal.
        /// </summary>
        public LecturerProfile LecturerProfile { get; set; }

        /// <summary>
        /// Navigation property for the list of supporting documents.
        /// These are encrypted files attached to substantiate the claim.
        /// </summary>
        public List<SupportingDoc> SupportingDocs { get; set; } = new();
    }
}
