// =====================================================================================
// Name: Luc de Marillac St Julien
// Student Number: ST10382638
// Group: 1
//
// References:
//   1) Project outline/instructions: https://chatgpt.com/c/68f2c6ad-b79c-832c-97a1-59b6f53334a9
//   2) C# Reference & Tutorials:   https://www.w3schools.com/cs/index.php
// =====================================================================================

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ST10382638_PROG_POE.Models
{
    /// <summary>
    /// Represents a supporting document uploaded with a claim.
    /// Each document is stored as an encrypted file and contains metadata
    /// about its original name, file type, and relative storage path.
    /// </summary>
    public class SupportingDoc
    {
        /// <summary>
        /// Primary key identifier for the document.
        /// Auto-generated by the database.
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int DocumentId { get; set; }

        /// <summary>
        /// Foreign key referencing the owning <see cref="Claim"/>.
        /// Ensures documents are always linked to a claim.
        /// </summary>
        [Required]
        public int ClaimId { get; set; }

        /// <summary>
        /// Original file name as uploaded by the user.
        /// Useful for display purposes in the UI.
        /// </summary>
        [Required]
        public string FileName { get; set; }

        /// <summary>
        /// Relative or absolute path pointing to the encrypted file (.enc).
        /// Used by the system to locate the stored document for decryption/download.
        /// </summary>
        [Required]
        public string FileUrl { get; set; }

        /// <summary>
        /// MIME type of the uploaded document (e.g., application/pdf, application/vnd.openxmlformats).
        /// Useful for filtering or display in UI components.
        /// </summary>
        [Required]
        public string FileType { get; set; }

        /// <summary>
        /// Navigation property to the related <see cref="Claim"/>.
        /// Allows traversal from a document back to its claim.
        /// </summary>
        public Claim Claim { get; set; }
    }
}
